-- Drop tables
DROP TABLE IF EXISTS iot.devices;
DROP TABLE IF EXISTS iot.sensors;
DROP TABLE IF EXISTS iot.sensor_data;

-- Drop tags
DROP TAG IF EXISTS iot.GEOSPATIAL_DATA_TAG;
DROP TAG IF EXISTS iot.JSON_DATA_TAG;
DROP TAG IF EXISTS iot.TIME_SERIES_DATA_TAG;
DROP TAG IF EXISTS iot.SENSOR_DATA_TAG;

-- Drop schema and database
DROP SCHEMA IF EXISTS iot;
DROP DATABASE IF EXISTS iotdb; 