site_name: Fru Dev
site_description: Comprehensive tutorials and guides for data science, AI, and development
site_author: Fru Dev
site_url: https://fd-tutorials.com

# Repository
repo_name: fd-docs
repo_url: https://github.com/frunde/fd-docs
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    search: material/magnify
    previous: material/arrow-left
    next: material/arrow-right
    top: material/arrow-up
    home: material/home

# Plugins
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: frunde
      repo: fd-docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
  - Tutorials:
    - Snowflake:
      - Data Quality Metrics: tutorials/snowflake/data-quality-metrics.md
      - Higher Order Functions: tutorials/snowflake/higher-order-functions.md
      - Data Classification: tutorials/snowflake/data-classification.md
      - ASOF JOIN: tutorials/snowflake/asof-join.md
      - Fuzzy Matching: tutorials/snowflake/fuzzy-matching.md
      - Aggregation Policies: tutorials/snowflake/aggregation-policies.md
      - Projection Policies: tutorials/snowflake/projection-policies.md
      - Memoizable Functions: tutorials/snowflake/memoizable-functions.md
      - Dynamic Tables: tutorials/snowflake/dynamic-tables.md
      - Database Change Management: tutorials/snowflake/database-change-management.md
    - AI/ML:
      - Cortex ML Forecasting: tutorials/ai-ml/cortex-forecasting.md
      - Cortex Anomaly Detection: tutorials/ai-ml/cortex-anomaly-detection.md
      - Cortex Classification: tutorials/ai-ml/cortex-classification.md
      - Snowpark ML: tutorials/ai-ml/snowpark-ml.md
      - Embeddings & Vector Search: tutorials/ai-ml/embeddings-vector-search.md
      - Document AI: tutorials/ai-ml/document-ai.md
      - Cortex Finetuning: tutorials/ai-ml/cortex-finetuning.md
    - Data Engineering:
      - Streamlit Chatbot: tutorials/data-engineering/streamlit-chatbot.md
      - Universal Search: tutorials/data-engineering/universal-search.md
      - Co-Pilot: tutorials/data-engineering/co-pilot.md
    - Data Science:
      - Python Basics: tutorials/data-science/python-basics.md
      - Data Analysis: tutorials/data-science/data-analysis.md
      - Machine Learning: tutorials/data-science/machine-learning.md
    - Administration:
      - Trust Center: tutorials/admin/trust-center.md
      - Cost Insights: tutorials/admin/cost-insights.md
      - JMeter Load Testing: tutorials/admin/jmeter-load-testing.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/frunde
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/frunde
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/frunde
  generator: false

# Copyright
copyright: Copyright &copy; 2024 Fru Dev
