site_name: Fru Labs
site_description: DEVeloping the future of Data, AI, and Tech
site_author: Fru Dev
site_url: https://labs.fru.dev

# Repository
repo_name: fd-labs
repo_url: https://github.com/frulouis/fd-labs
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.svg
  favicon: assets/images/logo.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search
    - search.highlight
    - search.share
    - search.suggest
    - search.boost
    - toc.follow
    - toc.integrate
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    search: material/magnify
    previous: material/arrow-left
    next: material/arrow-right
    top: material/arrow-up
    home: material/home

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: frulouis
      repo: fd-labs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Labs: 
    - Overview: labs/index.md
    - Snowflake: 
      - Overview: labs/snowflake/index.md
      - Common Models:
        - SalesDB: labs/snowflake/common-models/salesdb-data-model.md
        - CaresDB: labs/snowflake/common-models/caresdb-data-model.md
        - IoTDB: labs/snowflake/common-models/iotdb-data-model.md
        - MediSnowDB: labs/snowflake/common-models/medisnowdb-data-model.md
        - OrdersDB: labs/snowflake/common-models/ordersdb-data-model.md
      - Data Warehousing:
        - Data Classification: labs/snowflake/advanced-warehousing/data-classification.md
        - Data Quality Metrics: labs/snowflake/advanced-warehousing/data-quality-metrics.md
        - Dynamic Tables: labs/snowflake/advanced-warehousing/dynamic-tables.md
        - Higher Order Functions: labs/snowflake/advanced-warehousing/higher-order-functions.md
      - Data Engineering:
        - Python Basics: labs/snowflake/data-science/python-basics.md
      - Data Lake:
        - Coming Soon: labs/snowflake/data-lake/index.md
      - Classic AI/ML:
        - Snowpark ML: labs/snowflake/classic-ai-ml/snowpark-ml.md
      - Gen AI/LLMs:
        - Cortex AI: labs/snowflake/gen-ai-llms/cortex-ai.md
        - Embeddings & Vector Search: labs/snowflake/gen-ai-llms/embeddings-vector-search.md
      - Applications:
        - Streamlit Apps: labs/snowflake/applications/streamlit-apps.md
      - Collaboration:
        - Data Sharing: labs/snowflake/collaboration-sharing/index.md
      - Admins:
        - Admin Operations: labs/snowflake/admins-ops/index.md
      - Resources: labs/snowflake/resources.md
    - Dev Tools: labs/dev-tools/index.md
    - Blog: labs/thought-leadership/index.md
  - Subscribe: subscribe.md
  - Community: community.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/frulouis
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/frulouis
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/frulouis
  generator: false

# Copyright
copyright: Copyright &copy; 2025 Fru Dev | DEVeloping the future of Data, AI, and Tech
