site_name: Fru Dev
site_description: Comprehensive tutorials and guides for data science, AI, and development
site_author: Fru Dev
site_url: https://fd-tutorials.com

# Repository
repo_name: fd-docs
repo_url: https://github.com/frunde/fd-docs
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - search.boost
    - toc.follow
    - toc.integrate
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    search: material/magnify
    previous: material/arrow-left
    next: material/arrow-right
    top: material/arrow-up
    home: material/home

# Plugins
plugins:
  - search:
      lang: en
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+'
      min_search_length: 2
      prebuild_index: true
  - minify:
      minify_html: true

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: frunde
      repo: fd-docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
  - Common Models:
    - Data Quality Metrics: tutorials/common-models/data-quality-metrics.md
    - Higher Order Functions: tutorials/common-models/higher-order-functions.md
    - Dynamic Tables: tutorials/common-models/dynamic-tables.md
    - SalesDB Data Model: tutorials/common-models/salesdb-data-model.md
    - CaresDB Data Model: tutorials/common-models/caresdb-data-model.md
    - OrdersDB Data Model: tutorials/common-models/ordersdb-data-model.md
    - IoTDB Data Model: tutorials/common-models/iotdb-data-model.md
    - MediSnowDB Data Model: tutorials/common-models/medisnowdb-data-model.md
  - Advanced Warehousing:
    - Data Classification: tutorials/advanced-warehousing/data-classification.md
    - ASOF JOIN: tutorials/advanced-warehousing/asof-join.md
    - Fuzzy Matching: tutorials/advanced-warehousing/fuzzy-matching.md
  - Engineering / Lake:
    - Database Change Management: tutorials/engineering-lake/database-change-management.md
    - Data Lake Architecture: tutorials/engineering-lake/data-lake-architecture.md
    - ETL Pipelines: tutorials/engineering-lake/etl-pipelines.md
  - Classic AI/ML:
    - Snowpark ML: tutorials/classic-ai-ml/snowpark-ml.md
    - Model Training: tutorials/classic-ai-ml/model-training.md
    - Feature Engineering: tutorials/classic-ai-ml/feature-engineering.md
  - Gen AI / LLMs:
    - Embeddings & Vector Search: tutorials/gen-ai-llms/embeddings-vector-search.md
    - Cortex AI: tutorials/gen-ai-llms/cortex-ai.md
    - Document AI: tutorials/gen-ai-llms/document-ai.md
  - Applications:
    - Streamlit Apps: tutorials/applications/streamlit-apps.md
    - Universal Search: tutorials/applications/universal-search.md
    - Co-Pilot Integration: tutorials/applications/co-pilot-integration.md
  - Collaboration / Sharing:
    - Data Sharing: tutorials/collaboration-sharing/data-sharing.md
    - Marketplace: tutorials/collaboration-sharing/marketplace.md
    - Cross-Cloud: tutorials/collaboration-sharing/cross-cloud.md
  - Admins / Ops:
    - Trust Center: tutorials/admins-ops/trust-center.md
    - Cost Insights: tutorials/admins-ops/cost-insights.md
    - Performance Monitoring: tutorials/admins-ops/performance-monitoring.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/frunde
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/frunde
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/frunde
  generator: false

# Copyright
copyright: Copyright &copy; 2025 Fru Dev
